login/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'login'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_confirm', TemplateView.as_view(template_name='registration/delete_confirm.html'), name='delete-confirmation'),
    path('delete_complete', views.DeleteView.as_view(), name='delete-complete'),
    path('change/', views.UserChangeView.as_view(), name="change"),
    #path('Logout', TemplateView.as_view(template_name='registration/beforlogout.html'), name='out'),
]

pbl2aApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('', )
=======
    path('login/', include('login.urls')),
>>>>>>> ed179e374f379d614c5feb07343f6dc59a9f6f88
]

login/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            #username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin=True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('氏名'), max_length=50, blank=False,unique=False)
    kana_characters = models.CharField(_('カタカナ'), max_length=50, blank=True)
    nickname = models.CharField(_('ニックネーム'), max_length=50, blank=False)
    email = models.EmailField(_('email address'), unique=True)

    school_classification = models.CharField(_('学校区分'), max_length=10)
    school_name = models.CharField(_('学校名'), max_length=15)
    Department = models.CharField(_('学科'), max_length=10)
    student_number = models.CharField(_('学籍番号'), max_length=10)
    grade = models.CharField(_('学年'), max_length=1, blank=True)
    
    #icon = models.ImageField(upload_to="media",blank=True, null=True)
    introduction = models.CharField(max_length=75, blank=True, null=True)
    followers = models.ManyToManyField('self', blank=True, symmetrical=False)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    
    objects = UserManager()

    #EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm
User = get_user_model()


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        """
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
        """
        fields = ('email',)
                
                
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs.update({'placeholder': '8文字以上のパスワード',})
        self.fields['password2'].widget.attrs.update({'placeholder': '8文字以上のパスワード',})

class UserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'kana_characters',
            'nickname',
            'school_classification',
            'school_name',
            'Department',
            'student_number',
            'grade',
            
            #'icon'
        ]

    def __init__(self,nickname=None, username=None,grade=None, *args, **kwargs):
        #kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        # ユーザーの更新前情報をフォームに挿入
        if nickname:
            self.fields['nickname'].widget.attrs['value'] = nickname
        if username:
            self.fields['username'].widget.attrs['value'] = username
            
        if grade:
            self.fields['grade'].widget.attrs['value'] = grade

    def update(self, user):
        user.username = self.cleaned_data['username']
        user.nickname = self.cleaned_data['nickname']
        user.grade = self.cleaned_data['grade']
        #if self.cleaned_data['icon']:
         #   user.icon = self.cleaned_data['icon']        
        user.save()

login/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import (
     get_user_model, logout as auth_logout,
)
from .forms import UserCreateForm,UserChangeForm
from .models import User
from django.views.generic import FormView

<<<<<<< HEAD
# Create your views here.

class views():
    
    def signup_view():
        pass
    
    def signin_view():
        pass    
    
    def signout_view():
        pass
    
    
=======
User = get_user_model()

class SignUpView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login:profile')
    template_name = 'login/signup.html'


class ProfileView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        return render(self.request,'login/profile.html')   
    


class DeleteView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        user = User.objects.get(email=self.request.user.email)
        user.is_active = False
        user.save()
        auth_logout(self.request)
        return render(self.request,'login/delete_complete.html')

class UserChangeView(LoginRequiredMixin, FormView):
    template_name = 'login/change.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('login:profile')
    
    def form_valid(self, form):
        #formのupdateメソッドにログインユーザーを渡して更新
        form.update(user=self.request.user)
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # 更新前のユーザー情報をkwargsとして渡す
        kwargs.update({
            'username' : self.request.user.username,
            'nickname' : self.request.user.nickname,
            'grade' : self.request.user.grade,
        })        
        return kwargs
>>>>>>> ed179e374f379d614c5feb07343f6dc59a9f6f88

templates/login/change.html
{% block content %}
	<div>
    	<h5 class="card-title text-center">プロフィール変更</h5>
    	<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
        	<button type="submit" class="btn btn-primary btn-block">変更</button>
    	</form>
    </div>
    <div>
    	<a href="{% url 'login:profile' %}">プロフィールに戻る</a>
    </div>	
{% endblock %}

templates/login/delete_complete.html
{% block body %}

    <p>アカウントを削除しました。</p>

{% endblock %}

templates/login/delete_confirm.html
{% block content %}

    <p>アカウントを削除します。よろしいですか?</p>
    <a class="btn btn-danger" href="{% url 'accounts:delete-complete' %}">はい</a>

{% endblock %}

templates/login/login.html
{% block content %}

    <h5 class="card-title text-center">ログイン</h5>
    <form action="{% url 'login' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-block">ログイン</button>
        <input type="hidden" name="next" value="{{ next }}"/>
        {% csrf_token %}
    </form>
    <!--<a href="{% url 'password_reset' %}">パスワードをお忘れですか?</a>-->


{% endblock %}

templates/login/plofile.html
{% load static %}

{% block content %}

    <table class="table borderless">
        <tbody>
            <!--
        <tr>

            <th scope="row">icon</th>
            <td>{% if user.icon %}
			<img src="{{ user.icon.url }}" class="user-icon">
			{% else %}
			<img src="{% static 'images/black.png' %}" class="user-icon">
			{% endif %}</td>
        </tr>
    -->
        <tr>
            <th scope="row">氏名</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th scope="row">ニックネーム</th>
            <td>{{ user.nickname }}</td>
        </tr>
        <tr>
            <th scope="row">学年</th>
            <td>{{ user.grade }}</td>
        </tr>
        <tr>
            <th scope="row">E-mail</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th scope="row">入会日</th>
            <td>{{ user.date_joined }}</td>
        </tr>
        
        </tbody>
    </table>
    <a class="ui button" href="{% url 'login:change' %}">プロフィール情報変更</a>
    <style type="text/css">
    	.user-icon {
    	height: 80px;
    	width: 80px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
		}
	</style>

{% endblock %}

templates/login/profile.html
{% block content %}

    <table class="table borderless">
        <tbody>

        <tr>
            <th scope="row">氏名</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th scope="row">カタカナ</th>
            <td>{{ user.kana_characters }}</td>
        </tr>
        <tr>
            <th scope="row">ニックネーム</th>
            <td>{{ user.nickname }}</td>
        </tr>
        <tr>
            <th scope="row">E-mail</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th scope="row">学校区分</th>
            <td>{{ user.school_classification }}</td>
        </tr>
        <tr>
            <th scope="row">学校区分</th>
            <td>{{ user.school_name }}</td>
        </tr>
        <tr>
            <th scope="row">学科</th>
            <td>{{ user.Department }}</td>
        </tr>
        <tr>
            <th scope="row">学籍番号</th>
            <td>{{ user.student_number }}</td>
        </tr>
        <tr>
            <th scope="row">学年</th>
            <td>{{ user.grade }}</td>
        </tr>
        <tr>
            <th scope="row">入会日</th>
            <td>{{ user.date_joined }}</td>
        </tr>        
        </tbody>
    </table>
    <a class="ui button" href="{% url 'login:change' %}">プロフィール情報変更</a>
    <style type="text/css">
    	.user-icon {
    	height: 80px;
    	width: 80px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
		}
	</style>

{% endblock %}

templates/login/signup.html
{% block content %}

    <h5>入会</h5>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">入会</button>
    </form>

{% endblock %}